# Version vom 9.6.2026 (neu mit einigen Kommentaren für alternative Ports)
services:
  webserver:
    image: php:8.4-apache # PHP inkl. Apache2-Webserver
    restart: always # oder "no" wenn es bei Start von Docker nicht automatisch gestartet werden soll
    ports:
      - "80:80" # alternative Ports: "3000:80" oder "8000:80"" (intern, d.h. zweite Zahl immer auf 80 lassen)
    volumes: # lokales Volume "src" mounten in /var/www/html
      - ./src:/var/www/html
    environment:
      - TZ=Europe/Berlin  # Deutsche Zeitzone, bringt aber nichts für PHP
    # Extensions mysqli, PDO und mod_rewrite installieren
    command: bash -c "docker-php-ext-install mysqli pdo pdo_mysql && a2enmod rewrite && apache2-foreground"
  
  db:
    image: mariadb # neueste Version von MariaDB
    restart: always # oder "no" wenn es bei Start von Docker nicht automatisch gestartet werden soll
    ports:
      - "3306:3306" # alternativer Port: "3307:3306" (intern, d.h. zweite Zahl immer auf 3306 lassen)
    environment: # ggf. Passwörter anpassen, aber dann auch unten bei phpmyadmin ändern!
      MYSQL_ROOT_PASSWORD: rootpasswort
      MYSQL_DATABASE: meine_db
      MYSQL_USER: benutzer
      MYSQL_PASSWORD: benutzerpasswort
      TZ: Europe/Berlin  # Deutsche Zeitzone
    volumes: # persitente Speichern der Datenbank
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin # aktuelle Version
    restart: always # oder "no" wenn es bei Start von Docker nicht automatisch gestartet werden soll
    ports:
      - "8081:80" # alternativer Port: "8082:80" (intern, d.h. zweite Zahl immer auf 80 lassen)
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpasswort

volumes:
  db_data: